language: java
script: ant debug
jdk: oraclejdk7
env: 
  global: 
  - secure: PH1WN+UTpuEuI2gV5AOU9SpgYKpzYYBh7tHRtk7RNqarMBDo/ypjDPpcpTQkRKzoT7WOhMNl+2DhOsKpDyCEF4cSPOeWy9GuKMfm4FwO2+4tauwiC5zwgu3mQgiHwtIbA3no38ZuSyS389kns0OldCI3gY2noj/K8K1ZrBNy0sI=
  - secure: OSNKrEvPAypoe6dswENUBFKog2jG4XtfL4IgPgtqb7Rxs5Z5LWTOqTXUcmLhKRkRMmJRYzsb3fiG1PfKgQ2UE/d8jNVouohymzQuUznZlt++tqy+ypnjcunMhhy0JbmM3yQ+zKJs8hxIutTefkEByHm8/OiCPReMF9kUwE6rd4k=
  - secure: R7tjDaXbcH4/f8pTgpkjsx71TmtUvtPZyqaV03frdGmxKqMOfm8YWKSPHJe/woIgL9H5sIKJr/4AoPqWaxl7+qsx8gyCEFGioDeBHQ/CwfKfLZD1IF8rcmNOhyJcGwHt/VL9mf83zPzxogmyf4pcF+cRqTE2sSa3PNYGaVX7CKQ=
after_success: 
- curl --ftp-create-dirs -T "MainActivity-v1.0-b1.apk" -u $TABETAUSR:$TABETAPWD "ftp://$TABETAURL/Android/"
before_script: 
- wait_for_emulator
before_install: 
- sudo apt-get update -qq
- sudo apt-get install -qq libstdc++6:i386 lib32z1
- export COMPONENTS=build-tools-18.1.0,android-16,sysimg-16,extra-android-support
- curl -L https://raw.github.com/embarkmobile/android-sdk-installer/master/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
- source ~/.android-sdk-installer/env
- echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
